# shellcheck shell=bash
# InferHaven single-source-of-truth tool-config sync driver.
#
# Replaces 7 _sync_*_models() functions in haven.sh and 7 configure_*_ollama()
# functions in install-assistants.sh. Each tool is a renderer here; shared
# helpers (model fetch, ctx lookup, atomic write) live in haven-models.sh.
#
# Public API:
#   _haven_sync <tool>            — sync one tool
#   _haven_sync_all               — sync every supported tool in parallel
#
# Supported tools: opencode, aider, qwencode, pi, goose, continue, avante.
#
# Sentinel convention:
#   - Files: first-line marker `# _haven: managed`, `## inferhaven:managed`,
#     `-- _haven: managed`, or top-level JSON key `_haven: "managed"`.
#   - Sidecars: `~/<tool>/.inferhaven-managed` (used for OpenCode, Qwen).
# If sentinel is missing on an existing file, sync skips it (user owns the file).

# shellcheck source=/dev/null
. /usr/local/lib/haven/haven-models.sh
# shellcheck source=/dev/null
. /usr/local/lib/haven/haven-log.sh

HAVEN_SUPPORTED_TOOLS="opencode aider qwencode pi goose continue avante"

# Atomic file write: caller pipes content to stdin, passes target path.
_haven_atomic_write() {
    local target="$1"
    local mode="${2:-600}"
    mkdir -p "$(dirname "${target}")"
    local tmp
    tmp=$(mktemp "${target}.XXXXXX")
    cat > "${tmp}"
    chmod "${mode}" "${tmp}"
    mv "${tmp}" "${target}"
}

# Returns 0 if file may be (re)written, 1 if user owns it.
# new_ok=1 = treat absent file as ours; sentinel = required first-line marker.
_haven_sentinel_ok() {
    local file="$1" sentinel="$2"
    [ -f "${file}" ] && [ -s "${file}" ] || return 0    # absent/empty → ours
    head -1 "${file}" 2>/dev/null | grep -qF -- "${sentinel}"
}

# ── Renderers ────────────────────────────────────────────────────────────────

_haven_render_opencode() {
    local cfg_dir="${HOME}/.config/opencode"
    local cfg_path
    if [ -f "${cfg_dir}/settings.json" ]; then
        cfg_path="${cfg_dir}/settings.json"
    else
        cfg_path="${cfg_dir}/config.json"
    fi
    local sidecar="${cfg_dir}/.inferhaven-managed"
    local url; url=$(_haven_ollama_url)

    # User-managed if file exists with no sidecar AND has a custom provider section.
    if [ -f "${cfg_path}" ] && [ ! -f "${sidecar}" ] \
        && jq -e '.provider' "${cfg_path}" >/dev/null 2>&1; then
        log_private "opencode: user-managed (no sidecar) — skip"
        return 0
    fi

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then
        names="${DEFAULT_MODEL}"
    fi
    [ -z "${names}" ] && { log_private "opencode: no models — skip"; return 0; }

    local block="" first=1 model="" ctx=""
    while IFS= read -r model; do
        [ -z "${model}" ] && continue
        ctx=$(_haven_model_ctx "${model}")
        if [ "${first}" = 1 ]; then first=0; else block="${block},"$'\n'; fi
        block="${block}        \"${model}\": { \"tools\": true, \"limit\": { \"context\": ${ctx}, \"output\": 8192 } }"
    done <<< "${names}"

    cat << EOF | _haven_atomic_write "${cfg_path}"
{
  "\$schema": "https://opencode.ai/config.json",
  "provider": {
    "ollama": {
      "npm": "@ai-sdk/openai-compatible",
      "name": "Ollama Local",
      "options": { "baseURL": "${url}/v1" },
      "models": {
${block}
      }
    }
  }
}
EOF
    touch "${sidecar}"
    log "opencode: synced"
}

_haven_render_aider() {
    local conf="${HOME}/.aider.conf.yml"
    local model_settings="${HOME}/.aider.model.settings.yml"
    local inferhaven="${HOME}/.inferhaven"
    local url; url=$(_haven_ollama_url)
    local sentinel="## inferhaven:managed"

    # Always export OLLAMA_API_BASE
    touch "${inferhaven}"
    sed -i "/^export OLLAMA_API_BASE=/d" "${inferhaven}"
    printf 'export OLLAMA_API_BASE="%s"\n' "${url}" >> "${inferhaven}"

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then
        names="${DEFAULT_MODEL}"
    fi
    [ -z "${names}" ] && return 0

    # Main config — only if absent (cloud key path may have written it)
    if [ ! -f "${conf}" ]; then
        local first; first=$(printf '%s\n' "${names}" | head -1)
        cat << EOF | _haven_atomic_write "${conf}"
## Aider configuration — auto-generated by InferHaven
## Edit freely; will not be overwritten on restart.
model: ollama_chat/${first}
EOF
    fi

    # Model settings — sentinel-gated
    _haven_sentinel_ok "${model_settings}" "${sentinel}" || {
        log_private "aider: user-managed model settings — skip"
        return 0
    }

    {
        printf '%s\n' "${sentinel}"
        printf '%s\n' "## https://aider.chat/docs/config/adv-model-settings.html"
        printf '%s\n' "## Remove the first line above to opt out of auto-sync."
        local model ctx
        while IFS= read -r model; do
            [ -z "${model}" ] && continue
            ctx=$(_haven_model_ctx "${model}")
            printf '\n- name: ollama_chat/%s\n  extra_params:\n    num_ctx: %s\n' "${model}" "${ctx}"
        done <<< "${names}"
    } | _haven_atomic_write "${model_settings}"

    log "aider: synced"
}

_haven_render_qwencode() {
    local settings="${HOME}/.qwen/settings.json"
    local sidecar="${HOME}/.qwen/.inferhaven-managed"
    local inferhaven="${HOME}/.inferhaven"
    local url; url=$(_haven_ollama_url)

    touch "${inferhaven}"
    sed -i "/^export OLLAMA_API_KEY=/d" "${inferhaven}"
    printf 'export OLLAMA_API_KEY="ollama"\n' >> "${inferhaven}"

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then names="${DEFAULT_MODEL}"; fi
    [ -z "${names}" ] && return 0

    # Build managed-model JSON array
    local models_array
    models_array=$(
        while IFS= read -r model; do
            [ -z "${model}" ] && continue
            local ctx; ctx=$(_haven_model_ctx "${model}")
            jq -n \
                --arg id "${model}" \
                --arg name "${model} (Ollama)" \
                --arg baseUrl "${url}/v1" \
                --argjson ctx "${ctx}" \
                '{
                    id: $id, name: $name, envKey: "OLLAMA_API_KEY", baseUrl: $baseUrl,
                    generationConfig: { timeout: 300000, maxRetries: 1,
                        contextWindowSize: $ctx,
                        samplingParams: { max_tokens: 4096 } }
                }'
        done <<< "${names}" | jq -sc '.'
    )

    mkdir -p "$(dirname "${settings}")"

    if [ ! -f "${settings}" ]; then
        jq -n --argjson models "${models_array}" '
            { security: { auth: { selectedType: "openai" } },
              model: { name: ($models[0].id // "") },
              env: { OLLAMA_API_KEY: "ollama" },
              modelProviders: { openai: $models } }
        ' | _haven_atomic_write "${settings}"
        printf '%s' "${models_array}" | jq '[.[].id]' > "${sidecar}"
        log "qwencode: synced (fresh)"
        return 0
    fi

    if [ ! -f "${sidecar}" ]; then
        log_private "qwencode: user-managed (no sidecar) — skip"
        return 0
    fi

    local managed_ids; managed_ids=$(cat "${sidecar}" 2>/dev/null || echo "[]")
    jq --argjson new_models "${models_array}" --argjson ids "${managed_ids}" '
        .modelProviders.openai = (
            ((.modelProviders.openai // []) | map(select(.id as $id | ($ids | any(. == $id)) | not)))
            + $new_models
        )
        | .env.OLLAMA_API_KEY = "ollama"
        | .security.auth.selectedType = "openai"
        | .model.name = ($new_models[0].id // .model.name // "")
    ' "${settings}" | _haven_atomic_write "${settings}"
    printf '%s' "${models_array}" | jq '[.[].id]' > "${sidecar}"
    log "qwencode: synced (merge)"
}

_haven_render_pi() {
    local models_file="${HOME}/.pi/agent/models.json"
    local settings_file="${HOME}/.pi/agent/settings.json"
    local url; url=$(_haven_ollama_url)

    if [ ! -f "${settings_file}" ]; then
        jq -n '{ compaction: { enabled: true, reserveTokens: 4096, keepRecentTokens: 8192 } }' \
            | _haven_atomic_write "${settings_file}"
    fi

    if [ -f "${models_file}" ] && ! jq -e '._haven == "managed"' "${models_file}" >/dev/null 2>&1; then
        log_private "pi: user-managed (no _haven sentinel) — skip"
        return 0
    fi

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then names="${DEFAULT_MODEL}"; fi
    [ -z "${names}" ] && return 0

    local models_array
    models_array=$(
        while IFS= read -r model; do
            [ -z "${model}" ] && continue
            local ctx; ctx=$(_haven_model_ctx "${model}")
            jq -n --arg id "${model}" --argjson ctx "${ctx}" \
                '{ id: $id, contextWindow: $ctx, maxTokens: 8192,
                   cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 } }'
        done <<< "${names}" | jq -sc '.'
    )

    jq -n --arg baseUrl "${url}/v1" --argjson models "${models_array}" '
        { _haven: "managed",
          providers: { ollama: {
              baseUrl: $baseUrl, api: "openai-completions", apiKey: "ollama",
              compat: { supportsDeveloperRole: false, supportsReasoningEffort: false },
              models: $models } } }
    ' | _haven_atomic_write "${models_file}"
    log "pi: synced"
}

_haven_render_goose() {
    local config="${HOME}/.config/goose/config.yaml"
    local url; url=$(_haven_ollama_url)
    local inferhaven="${HOME}/.inferhaven"
    local sentinel="# _haven: managed"

    _haven_sentinel_ok "${config}" "${sentinel}" || {
        log_private "goose: user-managed — skip"
        return 0
    }

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then names="${DEFAULT_MODEL}"; fi
    [ -z "${names}" ] && return 0

    local first ctx
    first=$(printf '%s\n' "${names}" | head -1)
    ctx=$(_haven_model_ctx "${first}")

    touch "${inferhaven}"
    sed -i "/^export OLLAMA_CONTEXT_LENGTH=/d" "${inferhaven}"
    printf 'export OLLAMA_CONTEXT_LENGTH="%s"\n' "${ctx}" >> "${inferhaven}"

    cat << EOF | _haven_atomic_write "${config}"
${sentinel}
# InferHaven auto-generated — remove the first line above to opt out of auto-sync.
GOOSE_PROVIDER: ollama
GOOSE_MODEL: ${first}
OLLAMA_HOST: ${url}
EOF
    log "goose: synced"
}

_haven_render_continue() {
    local config="${HOME}/.continue/config.yaml"
    local url; url=$(_haven_ollama_url)
    local sentinel="# _haven: managed"

    _haven_sentinel_ok "${config}" "${sentinel}" || {
        # If file has user-defined models without sentinel, preserve completely
        if [ -f "${config}" ] && grep -q '^\s*- name:' "${config}" 2>/dev/null; then
            log_private "continue: user-defined models — skip"
            return 0
        fi
    }

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then names="${DEFAULT_MODEL}"; fi
    [ -z "${names}" ] && return 0

    [ -f "${HOME}/.inferhaven" ] && . "${HOME}/.inferhaven"

    {
        printf '%s\n' "${sentinel}"
        printf '%s\n' "# https://docs.continue.dev/reference"
        printf '%s\n' "name: InferHaven"
        printf '%s\n' "version: 1.0.0"
        printf '%s\n' "schema: v1"
        printf '%s\n' "models:"
        local model ctx _ml
        while IFS= read -r model; do
            [ -z "${model}" ] && continue
            ctx=$(_haven_model_ctx "${model}")
            printf '  - name: %s\n    provider: ollama\n    model: %s\n    apiBase: %s\n    contextLength: %s\n' \
                "${model}" "${model}" "${url}" "${ctx}"
            _ml=$(printf '%s' "${model}" | tr '[:upper:]' '[:lower:]')
            printf '    roles:\n      - chat\n      - edit\n'
            case "${_ml}" in
                *coder*|*codellama*|*codegemma*|*granite-code*) printf '      - autocomplete\n' ;;
            esac
            printf '      - apply\n'
        done <<< "${names}"
        # Cloud entries — only if API key set
        local pdef pname pprov pmodel penv pkey
        for pdef in \
            "Claude (cloud)|anthropic|claude-sonnet-4-6|ANTHROPIC_API_KEY" \
            "GPT-4o (cloud)|openai|gpt-4o|OPENAI_API_KEY" \
            "Gemini 2.0 Flash (cloud)|gemini|gemini-2.0-flash|GEMINI_API_KEY" \
            "OpenRouter (cloud)|openrouter|anthropic/claude-sonnet-4-6|OPENROUTER_API_KEY"; do
            IFS='|' read -r pname pprov pmodel penv <<< "${pdef}"
            eval "pkey=\"\${${penv}:-}\""
            [ -z "${pkey}" ] && continue
            printf '  - name: %s\n    provider: %s\n    model: %s\n    apiKey: %s\n    roles:\n      - chat\n      - edit\n      - apply\n' \
                "${pname}" "${pprov}" "${pmodel}" "${pkey}"
        done
        printf '%s\n' "# _haven: user-models — add models below this line; haven will never overwrite this section"
    } | _haven_atomic_write "${config}"

    # NOTE: We do NOT mirror to code-server. InferHaven manages the `cn` CLI in
    # this workspace container only; the code-server browser editor is the user's
    # to install/configure however they like. See docs/ide/continue.md.

    log "continue: synced"
}

_haven_render_avante() {
    local cfg_file="${HOME}/.config/nvim/lua/inferhaven-avante-config.lua"
    local plugin_file="${HOME}/.config/nvim/lua/plugins/avante.lua"
    local sentinel="-- _haven: managed"
    local url; url=$(_haven_ollama_url)

    [ -f "${cfg_file}" ] && ! head -1 "${cfg_file}" 2>/dev/null | grep -qF -- "${sentinel}" && {
        log_private "avante: user-managed — skip"
        return 0
    }

    local names; names=$(_haven_models_list)
    if [ -z "${names}" ] && [ -n "${DEFAULT_MODEL:-}" ]; then names="${DEFAULT_MODEL}"; fi
    [ -z "${names}" ] && return 0

    [ -f "${HOME}/.inferhaven" ] && . "${HOME}/.inferhaven"

    # Capture user-providers section (preserved across rewrites)
    local _user_providers=""
    if [ -f "${cfg_file}" ]; then
        _user_providers=$(awk '
            /^    -- _haven: user-providers/ { found=1; next }
            found && /^  },/ { exit }
            found { print }
        ' "${cfg_file}" 2>/dev/null || true)
    fi

    {
        printf '%s\n' "${sentinel}" \
            "-- InferHaven rewrites this file on model sync (haven pull/tune/remove)." \
            "-- Remove the first line above to manage this file yourself." \
            "return {"
        printf '  provider = "ollama",\n'
        printf '%s\n' "  providers = {"
        local _is_first=1 model ctx
        while IFS= read -r model; do
            [ -z "${model}" ] && continue
            ctx=$(_haven_model_ctx "${model}")
            if [ "${_is_first}" = 1 ]; then
                printf '    ollama = {\n'; _is_first=0
            else
                printf '    ["%s"] = {\n' "${model}"
            fi
            printf '      __inherited_from   = "openai",\n'
            printf '      endpoint           = "%s/v1",\n' "${url}"
            printf '      model              = "%s",\n' "${model}"
            printf '      api_key_name       = "OLLAMA_OPENAI_KEY",\n'
            printf '      timeout            = 120000,\n'
            printf '      extra_request_body = { options = { num_ctx = %s } },\n' "${ctx}"
            printf '    },\n'
        done <<< "${names}"
        [ -n "${ANTHROPIC_API_KEY:-}" ]  && printf '    claude     = { model = "claude-sonnet-4-6" },\n'
        [ -n "${OPENAI_API_KEY:-}" ]     && printf '    openai     = { model = "gpt-4o" },\n'
        [ -n "${GEMINI_API_KEY:-}" ]     && printf '    gemini     = { model = "gemini-2.0-flash" },\n'
        if [ -n "${OPENROUTER_API_KEY:-}" ]; then
            printf '%s\n' \
                "    openrouter = {" \
                "      __inherited_from = \"openai\"," \
                "      endpoint     = \"https://openrouter.ai/api/v1\"," \
                "      api_key_name = \"OPENROUTER_API_KEY\"," \
                "      model        = \"deepseek/deepseek-r1\"," \
                "    },"
        fi
        printf '    %s\n' "-- _haven: user-providers — add custom providers below; haven never overwrites this section"
        [ -n "${_user_providers}" ] && printf '%s\n' "${_user_providers}"
        printf '%s\n' "  }," "}"
    } | _haven_atomic_write "${cfg_file}"

    # Plugin file: write only if absent (function-form opts so sidecar reloads)
    if [ ! -f "${plugin_file}" ]; then
        cat << 'AVANTE_LUA' | _haven_atomic_write "${plugin_file}"
return {
  "yetone/avante.nvim",
  event = "VeryLazy",
  build = "make",
  opts = function()
    local ok, cfg = pcall(require, "inferhaven-avante-config")
    return ok and cfg or {}
  end,
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
  },
}
AVANTE_LUA
    fi
    log "avante: synced"
}

# ── Public dispatcher ─────────────────────────────────────────────────────────

_haven_sync() {
    local tool="$1"
    case "${tool}" in
        opencode)  _haven_render_opencode  "$@" ;;
        aider)     _haven_render_aider     "$@" ;;
        qwencode)  _haven_render_qwencode  "$@" ;;
        pi)        _haven_render_pi        "$@" ;;
        goose)     _haven_render_goose     "$@" ;;
        continue)  _haven_render_continue  "$@" ;;
        avante)    _haven_render_avante    "$@" ;;
        *)         log_private "_haven_sync: unknown tool '${tool}'"; return 1 ;;
    esac
}

# Run all 7 in parallel. Wall time = max(N) instead of sum(N).
_haven_sync_all() {
    _haven_models_warm    # populate cache once before parallel phase
    local pids=() tool
    for tool in ${HAVEN_SUPPORTED_TOOLS}; do
        _haven_sync "${tool}" &
        pids+=($!)
    done
    local rc=0
    for p in "${pids[@]}"; do
        wait "${p}" || rc=1
    done
    return "${rc}"
}
